/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacote;

/**
 *
 * @author LuanLuL
 */
public class PainelDeControle extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PainelDeControle.class.getName());

    /**
     * Creates new form PainelDeControle
     */
    public PainelDeControle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        lblSrvDesktop = new javax.swing.JLabel();
        lblLegSrvDesktop = new javax.swing.JLabel();
        btnControlDesktop = new javax.swing.JToggleButton();
        lblSrvWeb = new javax.swing.JLabel();
        lblLegSrvWeb = new javax.swing.JLabel();
        btnControlWeb = new javax.swing.JToggleButton();
        lblSrvTerceiro = new javax.swing.JLabel();
        lblLegSrvTerceiro = new javax.swing.JLabel();
        btnControlTerceiro = new javax.swing.JToggleButton();
        lblSrvPublicidade = new javax.swing.JLabel();
        lblLegSrvPublicidade = new javax.swing.JLabel();
        btnControlPublicidade = new javax.swing.JToggleButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Painel de Controle");
        setName("frmPainelDeControle"); // NOI18N

        lblSrvDesktop.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSrvDesktop.setText("Serviço Desktop");
        lblSrvDesktop.setToolTipText("");
        lblSrvDesktop.setName("lblSrvDesktop"); // NOI18N

        lblLegSrvDesktop.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblLegSrvDesktop.setForeground(new java.awt.Color(255, 0, 0));
        lblLegSrvDesktop.setText("Inpirado no WhatsApp Desktop");
        lblLegSrvDesktop.setName("lblLegSrvDesktop"); // NOI18N

        btnControlDesktop.setText("Ativar");
        btnControlDesktop.setName("btnControlDesktop"); // NOI18N
        btnControlDesktop.addActionListener(this::btnControlDesktopActionPerformed);

        lblSrvWeb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSrvWeb.setText("Serviço WEB");
        lblSrvWeb.setToolTipText("");
        lblSrvWeb.setName("lblSrvWeb"); // NOI18N

        lblLegSrvWeb.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblLegSrvWeb.setForeground(new java.awt.Color(255, 0, 0));
        lblLegSrvWeb.setText("Inpirado no WhatsApp Web");
        lblLegSrvWeb.setName("lblLegSrvWeb"); // NOI18N

        btnControlWeb.setText("Ativar");
        btnControlWeb.setName("btnControlrWeb"); // NOI18N
        btnControlWeb.addActionListener(this::btnControlWebActionPerformed);

        lblSrvTerceiro.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSrvTerceiro.setText("Serviço Terceiro");
        lblSrvTerceiro.setToolTipText("");
        lblSrvTerceiro.setName("lblSrvTerceiro"); // NOI18N

        lblLegSrvTerceiro.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblLegSrvTerceiro.setForeground(new java.awt.Color(255, 0, 0));
        lblLegSrvTerceiro.setText("Modulo Segunda Linguagem");
        lblLegSrvTerceiro.setName("lblLegSrvTerceiro"); // NOI18N

        btnControlTerceiro.setText("Ativar");
        btnControlTerceiro.setName("btnControlTerceiro"); // NOI18N
        btnControlTerceiro.addActionListener(this::btnControlTerceiroActionPerformed);

        lblSrvPublicidade.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSrvPublicidade.setText("Serviço Publicidade");
        lblSrvPublicidade.setToolTipText("");
        lblSrvPublicidade.setName("lblSrvPublicidade"); // NOI18N

        lblLegSrvPublicidade.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblLegSrvPublicidade.setForeground(new java.awt.Color(255, 0, 0));
        lblLegSrvPublicidade.setText("Envio de propaganda em multicast");
        lblLegSrvPublicidade.setName("lblLegSrvPublicidade"); // NOI18N

        btnControlPublicidade.setText("Ativar");
        btnControlPublicidade.setName("btnControlPublicidade"); // NOI18N
        btnControlPublicidade.addActionListener(this::btnControlPublicidadeActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSrvDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLegSrvDesktop)
                            .addComponent(lblSrvTerceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLegSrvTerceiro)
                            .addComponent(lblSrvWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLegSrvWeb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnControlWeb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(btnControlTerceiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnControlDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSrvPublicidade, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLegSrvPublicidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnControlPublicidade, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSrvDesktop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLegSrvDesktop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSrvWeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLegSrvWeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSrvTerceiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLegSrvTerceiro))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnControlDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
                            .addComponent(btnControlWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnControlTerceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSrvPublicidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLegSrvPublicidade))
                    .addComponent(btnControlPublicidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnControlDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlDesktopActionPerformed
        if(btnControlDesktop.isSelected()){
            btnControlDesktop.setText("Desativar");
            Util.threadDesktopRecepcaoThreads = new DesktopRecepcaoThreads();            
            Util.threadDesktopEnvioThreads = new DesktopEnvioThreads();
            Thread.ofVirtual().start(Util.threadDesktopRecepcaoThreads);
            Thread.ofVirtual().start(Util.threadDesktopEnvioThreads);
        } else {
            btnControlDesktop.setText("Ativar");
            Util.threadDesktopRecepcaoThreads.fecharServidor();
            Util.threadDesktopEnvioThreads.fecharServidor();
        }
    }//GEN-LAST:event_btnControlDesktopActionPerformed

    private void btnControlWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlWebActionPerformed
        if(btnControlWeb.isSelected()){
            btnControlWeb.setText("Desativar");
        } else {
            btnControlWeb.setText("Ativar");
        }
    }//GEN-LAST:event_btnControlWebActionPerformed

    private void btnControlTerceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlTerceiroActionPerformed
        if(btnControlTerceiro.isSelected()){
            btnControlTerceiro.setText("Desativar");
        } else {
            btnControlTerceiro.setText("Ativar");
        }
    }//GEN-LAST:event_btnControlTerceiroActionPerformed

    private void btnControlPublicidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlPublicidadeActionPerformed
        if(btnControlPublicidade.isSelected()){
            btnControlPublicidade.setText("Desativar");
        } else {
            btnControlPublicidade.setText("Ativar");
        }
    }//GEN-LAST:event_btnControlPublicidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PainelDeControle().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnControlDesktop;
    private javax.swing.JToggleButton btnControlPublicidade;
    private javax.swing.JToggleButton btnControlTerceiro;
    private javax.swing.JToggleButton btnControlWeb;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblLegSrvDesktop;
    private javax.swing.JLabel lblLegSrvPublicidade;
    private javax.swing.JLabel lblLegSrvTerceiro;
    private javax.swing.JLabel lblLegSrvWeb;
    private javax.swing.JLabel lblSrvDesktop;
    private javax.swing.JLabel lblSrvPublicidade;
    private javax.swing.JLabel lblSrvTerceiro;
    private javax.swing.JLabel lblSrvWeb;
    // End of variables declaration//GEN-END:variables
}
