/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacote;

/**
 *
 * @author LuanLuL
 */
public class frmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmLogin.class.getName());

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupCor = new javax.swing.ButtonGroup();
        btGroupAvatar = new javax.swing.ButtonGroup();
        lblNick = new javax.swing.JLabel();
        inputTxtNickname = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        rdCorVerde = new javax.swing.JRadioButton();
        rdCorAzul = new javax.swing.JRadioButton();
        rdCorRosa = new javax.swing.JRadioButton();
        lblAvatar = new javax.swing.JLabel();
        rdAvatarHomem = new javax.swing.JRadioButton();
        btnEntrar = new javax.swing.JButton();
        lblImgAvatarHomem = new javax.swing.JLabel();
        lblImgAvatarMulher = new javax.swing.JLabel();
        rdAvatarMulher = new javax.swing.JRadioButton();
        rdAvatarIndeterminado = new javax.swing.JRadioButton();
        lblImgAvatarIndeterminado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setName("frmLogin"); // NOI18N

        lblNick.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNick.setText("Nickname:");
        lblNick.setName("lblNick"); // NOI18N

        inputTxtNickname.setName("inputTxtNickname"); // NOI18N
        inputTxtNickname.addActionListener(this::inputTxtNicknameActionPerformed);

        lblCor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCor.setText("Cor:");
        lblCor.setName("lblCor"); // NOI18N

        btGroupCor.add(rdCorVerde);
        rdCorVerde.setForeground(new java.awt.Color(51, 255, 0));
        rdCorVerde.setText("Verde");
        rdCorVerde.setName("rdCorVerde"); // NOI18N
        rdCorVerde.addActionListener(this::rdCorVerdeActionPerformed);

        btGroupCor.add(rdCorAzul);
        rdCorAzul.setForeground(new java.awt.Color(51, 51, 255));
        rdCorAzul.setSelected(true);
        rdCorAzul.setLabel("Azul");
        rdCorAzul.setName("rdCorAzul"); // NOI18N
        rdCorAzul.addActionListener(this::rdCorAzulActionPerformed);

        btGroupCor.add(rdCorRosa);
        rdCorRosa.setForeground(new java.awt.Color(255, 0, 204));
        rdCorRosa.setText("Rosa");
        rdCorRosa.setName("rdCorRosa"); // NOI18N
        rdCorRosa.addActionListener(this::rdCorRosaActionPerformed);

        lblAvatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAvatar.setText("Avatar:");
        lblAvatar.setName("lblAvatar"); // NOI18N

        btGroupAvatar.add(rdAvatarHomem);
        rdAvatarHomem.setName("rdCorRosa"); // NOI18N
        rdAvatarHomem.addActionListener(this::rdAvatarHomemActionPerformed);

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);

        lblImgAvatarHomem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/images/AvatarHomem.png"))); // NOI18N
        lblImgAvatarHomem.setLabelFor(rdAvatarHomem);

        lblImgAvatarMulher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/images/AvatarMulher.png"))); // NOI18N
        lblImgAvatarMulher.setLabelFor(rdAvatarMulher);
        lblImgAvatarMulher.setName("lblImgAvatarMulher"); // NOI18N

        btGroupAvatar.add(rdAvatarMulher);
        rdAvatarMulher.setName("rdAvatarMulher"); // NOI18N
        rdAvatarMulher.addActionListener(this::rdAvatarMulherActionPerformed);

        btGroupAvatar.add(rdAvatarIndeterminado);
        rdAvatarIndeterminado.setSelected(true);
        rdAvatarIndeterminado.setName("rdAvatarIndeterminado"); // NOI18N
        rdAvatarIndeterminado.addActionListener(this::rdAvatarIndeterminadoActionPerformed);

        lblImgAvatarIndeterminado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/images/AvatarIndeterminado.png"))); // NOI18N
        lblImgAvatarIndeterminado.setLabelFor(rdAvatarIndeterminado);
        lblImgAvatarIndeterminado.setName("lblImgAvatarIndeterminado"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNick, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(inputTxtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(rdCorVerde))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(rdAvatarHomem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImgAvatarHomem)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdAvatarMulher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImgAvatarMulher))
                            .addComponent(rdCorAzul))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(rdCorRosa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(rdAvatarIndeterminado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImgAvatarIndeterminado)))))
                .addGap(0, 108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNick)
                    .addComponent(inputTxtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdCorVerde)
                            .addComponent(rdCorAzul)
                            .addComponent(rdCorRosa))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatar)
                    .addComponent(rdAvatarHomem)
                    .addComponent(lblImgAvatarHomem)
                    .addComponent(rdAvatarMulher)
                    .addComponent(lblImgAvatarMulher)
                    .addComponent(rdAvatarIndeterminado)
                    .addComponent(lblImgAvatarIndeterminado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblNick.getAccessibleContext().setAccessibleName("lblNick");
        inputTxtNickname.getAccessibleContext().setAccessibleName("inputTxtNickname");
        lblCor.getAccessibleContext().setAccessibleName("Cor");
        rdCorVerde.getAccessibleContext().setAccessibleName("rdCorVerde");
        rdCorRosa.getAccessibleContext().setAccessibleName("rdCorRosa");
        lblImgAvatarHomem.getAccessibleContext().setAccessibleName("lblImgAvatarHomem");
        lblImgAvatarMulher.getAccessibleContext().setAccessibleName("lblImgAvatarMulher");
        rdAvatarMulher.getAccessibleContext().setAccessibleName("rdAvatarMulher");
        rdAvatarIndeterminado.getAccessibleContext().setAccessibleName("rdAvatarIndeterminado");
        lblImgAvatarIndeterminado.getAccessibleContext().setAccessibleName("lblImgAvatarIndeterminado");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTxtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTxtNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTxtNicknameActionPerformed

    private void rdCorVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCorVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdCorVerdeActionPerformed

    private void rdCorRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCorRosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdCorRosaActionPerformed

    private void rdCorAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCorAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdCorAzulActionPerformed

    private void rdAvatarHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAvatarHomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAvatarHomemActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
       Util.nickname = inputTxtNickname.getText();
       
       if(rdCorAzul.isSelected()){
            Util.cor = "blue";
       } else if(rdCorRosa.isSelected()){
            Util.cor = "pink";
       } else {
            Util.cor = "green";
       }
       
       if(rdAvatarHomem.isSelected()){
            Util.avatar = "AvatarHomem.png";
       } else if(rdAvatarMulher.isSelected()){
            Util.avatar = "AvatarMulher.png";
       } else {
            Util.avatar = "AvatarIndeterminado.png";
       }
       
       frmChat fmrChat = new frmChat();
       fmrChat.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void rdAvatarMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAvatarMulherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAvatarMulherActionPerformed

    private void rdAvatarIndeterminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAvatarIndeterminadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAvatarIndeterminadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGroupAvatar;
    private javax.swing.ButtonGroup btGroupCor;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JTextField inputTxtNickname;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblImgAvatarHomem;
    private javax.swing.JLabel lblImgAvatarIndeterminado;
    private javax.swing.JLabel lblImgAvatarMulher;
    private javax.swing.JLabel lblNick;
    private javax.swing.JRadioButton rdAvatarHomem;
    private javax.swing.JRadioButton rdAvatarIndeterminado;
    private javax.swing.JRadioButton rdAvatarMulher;
    private javax.swing.JRadioButton rdCorAzul;
    private javax.swing.JRadioButton rdCorRosa;
    private javax.swing.JRadioButton rdCorVerde;
    // End of variables declaration//GEN-END:variables
}
